app:
  version: 0.1
  
# Configure the server to run with SSL/TLS and using HTTPS
server:
  port: 8443
  ssl:
    key-store: classpath:tomcat.keystore
    key-store-password: password
    key-password: password